from stock_risk_mcp.system_smoke import run_system_smoke


def test_system_smoke_validates_local_workflow(tmp_path) -> None:
    result = run_system_smoke(tmp_path / "smoke.sqlite3", tmp_path / "outputs")

    assert result["status"] in {"COMPLETED", "PARTIAL"}
    assert result["checks"]["db_migration"] is True
    assert result["checks"]["mock_connector_output"] is True
    assert result["checks"]["import"] is True
    assert result["checks"]["pipeline_run"] is True
    assert result["checks"]["dashboard_html"] is True
    assert result["checks"]["external_network_calls"] is False
    assert result["checks"]["strategy_fixture_run"] is True
    assert result["checks"]["strategy_backtest_fixture_run"] is True
    assert result["checks"]["technical_evidence_fixture_run"] is True
    assert result["checks"]["market_discovery_fixture_run"] is True
    assert result["checks"]["llm_feature_store_fixture_run"] is True
    assert result["checks"]["llm_signal_evaluation_fixture_run"] is True
    assert result["checks"]["trade_plan_fixture_run"] is True
    assert result["checks"]["paper_eval_fixture_run"] is True
    assert result["checks"]["policy_replay_fixture_run"] is True
    assert result["checks"]["llm_advisory_fixture_run"] is True
    assert result["checks"]["local_model_runtime_fixture_run"] is True
    assert result["checks"]["local_model_benchmark_fixture_run"] is True
    assert result["checks"]["local_model_decision_report_fixture_run"] is True
    assert result["checks"]["strategy_track_fixture_run"] is True
    assert result["checks"]["market_profit_fixture_run"] is True
    assert result["checks"]["domestic_realtime_fixture_run"] is True
    assert result["checks"]["domestic_scanner_fixture_run"] is True
    assert result["checks"]["domestic_candidate_evaluation_fixture_run"] is True
    assert result["checks"]["domestic_replay_fixture_run"] is True
    assert result["checks"]["domestic_calibration_fixture_run"] is True
    assert result["checks"]["domestic_paper_shadow_fixture_run"] is True
    assert result["checks"]["historical_data_fixture_run"] is True
    assert result["checks"]["historical_manifest_generated"] is True
    assert result["checks"]["historical_calendar_fixture_run"] is True
    assert result["checks"]["historical_calendar_manifest_generated"] is True
    assert result["checks"]["historical_replay_bridge_fixture_run"] is True
    assert result["checks"]["historical_replay_event_stream_generated"] is True
    assert result["checks"]["historical_replay_windows_generated"] is True
    assert result["checks"]["historical_replay_event_context_attached"] is True
    assert result["checks"]["historical_scanner_replay_input_generated"] is True
    assert result["checks"]["calendar_aware_windowing_enabled"] is True
    assert result["checks"]["holiday_sessions_not_counted_as_data_gaps"] is True
    assert result["checks"]["early_close_sessions_flagged"] is True
    assert result["checks"]["event_context_attached_report_only"] is True
    assert result["checks"]["scanner_replay_report_only"] is True
    assert result["checks"]["scanner_replay_non_order_candidate"] is True
    assert result["checks"]["historical_replay_read_only"] is True
    assert result["checks"]["historical_replay_non_executable"] is True
    assert result["checks"]["historical_replay_local_files_only"] is True
    assert result["checks"]["historical_replay_remote_fetch_allowed"] is False
    assert result["checks"]["historical_replay_api_provider_called"] is False
    assert result["checks"]["historical_replay_order_intent_created"] is False
    assert result["checks"]["historical_replay_live_or_prod_used"] is False
    assert result["checks"]["historical_replay_cloud_llm_called"] is False
    assert result["checks"]["historical_replay_model_runtime_called"] is False
    assert result["checks"]["historical_replay_ml_training_run"] is False
    assert result["checks"]["historical_outcome_observation_fixture_run"] is True
    assert result["checks"]["historical_outcome_windows_generated"] is True
    assert result["checks"]["historical_outcome_metrics_generated"] is True
    assert result["checks"]["historical_outcome_labels_report_only"] is True
    assert result["checks"]["historical_outcome_no_lookahead_guard_enabled"] is True
    assert result["checks"]["historical_outcome_scanner_input_not_mutated"] is True
    assert result["checks"]["historical_outcome_read_only"] is True
    assert result["checks"]["historical_outcome_non_executable"] is True
    assert result["checks"]["historical_outcome_local_files_only"] is True
    assert result["checks"]["historical_outcome_remote_fetch_allowed"] is False
    assert result["checks"]["historical_outcome_api_provider_called"] is False
    assert result["checks"]["historical_outcome_order_intent_created"] is False
    assert result["checks"]["historical_outcome_live_or_prod_used"] is False
    assert result["checks"]["historical_outcome_cloud_llm_called"] is False
    assert result["checks"]["historical_outcome_model_runtime_called"] is False
    assert result["checks"]["historical_outcome_ml_training_run"] is False
    assert result["checks"]["historical_dataset_assembly_fixture_run"] is True
    assert result["checks"]["historical_dataset_records_generated"] is True
    assert result["checks"]["historical_dataset_feature_outcome_separated"] is True
    assert result["checks"]["historical_dataset_no_lookahead_guard_enabled"] is True
    assert result["checks"]["historical_dataset_scanner_input_not_mutated"] is True
    assert result["checks"]["historical_dataset_report_only"] is True
    assert result["checks"]["historical_dataset_read_only"] is True
    assert result["checks"]["historical_dataset_non_executable"] is True
    assert result["checks"]["historical_dataset_local_files_only"] is True
    assert result["checks"]["historical_dataset_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_api_provider_called"] is False
    assert result["checks"]["historical_dataset_order_intent_created"] is False
    assert result["checks"]["historical_dataset_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_ml_training_run"] is False
    assert result["checks"]["historical_dataset_validation_fixture_run"] is True
    assert result["checks"]["historical_dataset_validation_report_generated"] is True
    assert result["checks"]["historical_dataset_leakage_audit_generated"] is True
    assert result["checks"]["historical_dataset_chronological_split_manifest_generated"] is True
    assert result["checks"]["historical_dataset_feature_outcome_leakage_absent"] is True
    assert result["checks"]["historical_dataset_split_is_chronological"] is True
    assert result["checks"]["historical_dataset_split_no_random_shuffle"] is True
    assert result["checks"]["historical_dataset_split_no_partition_overlap"] is True
    assert result["checks"]["historical_dataset_split_no_duplicate_record_ids"] is True
    assert result["checks"]["historical_dataset_coverage_report_generated"] is True
    assert result["checks"]["historical_dataset_label_distribution_generated"] is True
    assert result["checks"]["historical_dataset_validation_report_only"] is True
    assert result["checks"]["historical_dataset_validation_read_only"] is True
    assert result["checks"]["historical_dataset_validation_non_executable"] is True
    assert result["checks"]["historical_dataset_validation_local_files_only"] is True
    assert result["checks"]["historical_dataset_validation_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_validation_api_provider_called"] is False
    assert result["checks"]["historical_dataset_validation_order_intent_created"] is False
    assert result["checks"]["historical_dataset_validation_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_validation_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_validation_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_validation_ml_training_run"] is False
    assert result["checks"]["historical_dataset_readiness_fixture_run"] is True
    assert result["checks"]["historical_dataset_readiness_report_generated"] is True
    assert result["checks"]["historical_dataset_split_quality_report_generated"] is True
    assert result["checks"]["historical_dataset_imbalance_report_generated"] is True
    assert result["checks"]["historical_dataset_baseline_evaluation_generated"] is True
    assert result["checks"]["historical_dataset_baseline_non_learning"] is True
    assert result["checks"]["historical_dataset_readiness_report_only"] is True
    assert result["checks"]["historical_dataset_readiness_read_only"] is True
    assert result["checks"]["historical_dataset_readiness_non_executable"] is True
    assert result["checks"]["historical_dataset_readiness_local_files_only"] is True
    assert result["checks"]["historical_dataset_readiness_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_readiness_api_provider_called"] is False
    assert result["checks"]["historical_dataset_readiness_order_intent_created"] is False
    assert result["checks"]["historical_dataset_readiness_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_readiness_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_readiness_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_readiness_ml_training_run"] is False
    assert result["checks"]["historical_dataset_readiness_learned_model_evaluation_run"] is False
    assert result["checks"]["historical_dataset_readiness_ml_ready_tensor_export_created"] is False
    assert result["checks"]["historical_model_training_sandbox_fixture_run"] is True
    assert result["checks"]["historical_model_training_plan_check_generated"] is True
    assert result["checks"]["historical_model_training_run_report_generated"] is True
    assert result["checks"]["historical_model_evaluation_report_generated"] is True
    assert result["checks"]["historical_model_metrics_report_generated"] is True
    assert result["checks"]["historical_model_artifact_manifest_generated"] is True
    assert result["checks"]["historical_model_training_local_only"] is True
    assert result["checks"]["historical_model_training_offline_only"] is True
    assert result["checks"]["historical_model_training_chronological_split_used"] is True
    assert result["checks"]["historical_model_training_no_random_shuffle"] is True
    assert result["checks"]["historical_model_training_dummy_models_available"] is True
    assert result["checks"]["historical_model_training_optional_sklearn_fail_closed"] is True
    assert result["checks"]["historical_model_training_report_only"] is True
    assert result["checks"]["historical_model_training_non_executable"] is True
    assert result["checks"]["historical_model_training_no_runtime_signal"] is True
    assert result["checks"]["historical_model_training_no_order_candidate"] is True
    assert result["checks"]["historical_model_training_no_live_inference"] is True
    assert result["checks"]["historical_model_training_no_broker_path"] is True
    assert result["checks"]["historical_model_training_no_live_prod"] is True
    assert result["checks"]["historical_model_training_no_network"] is True
    assert result["checks"]["historical_model_training_no_cloud_llm"] is True
    assert result["checks"]["historical_model_training_no_local_llm_runtime"] is True
    assert result["checks"]["historical_model_experiment_registry_fixture_run"] is True
    assert result["checks"]["historical_model_experiment_registry_report_generated"] is True
    assert result["checks"]["historical_model_comparison_report_generated"] is True
    assert result["checks"]["historical_model_risk_review_generated"] is True
    assert result["checks"]["historical_model_promotion_block_report_generated"] is True
    assert result["checks"]["historical_model_experiment_lineage_report_generated"] is True
    assert result["checks"]["historical_model_experiment_report_only"] is True
    assert result["checks"]["historical_model_experiment_non_executable"] is True
    assert result["checks"]["historical_model_experiment_no_runtime_signal"] is True
    assert result["checks"]["historical_model_experiment_no_order_candidate"] is True
    assert result["checks"]["historical_model_experiment_no_live_inference"] is True
    assert result["checks"]["historical_model_experiment_no_deployment"] is True
    assert result["checks"]["historical_model_experiment_no_paper_trading"] is True
    assert result["checks"]["historical_model_experiment_no_broker_path"] is True
    assert result["checks"]["historical_model_experiment_no_live_prod"] is True
    assert result["checks"]["historical_model_experiment_no_network"] is True
    assert result["checks"]["historical_model_experiment_no_cloud_llm"] is True
    assert result["checks"]["historical_model_experiment_no_local_llm_runtime"] is True
    assert result["checks"]["historical_model_experiment_promotion_blocked_by_default"] is True
    assert result["checks"]["historical_signal_candidate_fixture_run"] is True
    assert result["checks"]["historical_signal_candidate_build_generated"] is True
    assert result["checks"]["historical_signal_candidate_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_safety_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_gap_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_audit_record_generated"] is True
    assert result["checks"]["historical_signal_candidate_report_only"] is True
    assert result["checks"]["historical_signal_candidate_non_executable"] is True
    assert result["checks"]["historical_signal_candidate_local_only"] is True
    assert result["checks"]["historical_signal_candidate_offline_only"] is True
    assert result["checks"]["historical_signal_candidate_no_runtime_signal"] is True
    assert result["checks"]["historical_signal_candidate_no_order_candidate"] is True
    assert result["checks"]["historical_signal_candidate_no_live_inference"] is True
    assert result["checks"]["historical_signal_candidate_no_deployment"] is True
    assert result["checks"]["historical_signal_candidate_no_paper_trading"] is True
    assert result["checks"]["historical_signal_candidate_no_broker_path"] is True
    assert result["checks"]["historical_signal_candidate_no_live_prod"] is True
    assert result["checks"]["historical_signal_candidate_no_network"] is True
    assert result["checks"]["historical_signal_candidate_no_provider_api"] is True
    assert result["checks"]["historical_signal_candidate_no_cloud_llm"] is True
    assert result["checks"]["historical_signal_candidate_no_local_llm_runtime"] is True
    assert result["checks"]["historical_signal_candidate_no_buy_sell_order_execution"] is True
    assert result["checks"]["historical_signal_candidate_parquet_unsupported"] is True
    assert result["checks"]["historical_paper_trading_fixture_run"] is True
    assert result["checks"]["historical_paper_trading_run_generated"] is True
    assert result["checks"]["historical_paper_trading_decision_generated"] is True
    assert result["checks"]["historical_paper_trading_order_intent_generated"] is True
    assert result["checks"]["historical_paper_trading_fill_generated"] is True
    assert result["checks"]["historical_paper_trading_ledger_generated"] is True
    assert result["checks"]["historical_paper_trading_position_generated"] is True
    assert result["checks"]["historical_paper_trading_trade_generated"] is True
    assert result["checks"]["historical_paper_trading_performance_report_generated"] is True
    assert result["checks"]["historical_paper_trading_safety_report_generated"] is True
    assert result["checks"]["historical_paper_trading_gap_report_generated"] is True
    assert result["checks"]["historical_paper_trading_audit_record_generated"] is True
    assert result["checks"]["historical_paper_trading_paper_only"] is True
    assert result["checks"]["historical_paper_trading_simulated_only"] is True
    assert result["checks"]["historical_paper_trading_non_executable"] is True
    assert result["checks"]["historical_paper_trading_local_only"] is True
    assert result["checks"]["historical_paper_trading_offline_only"] is True
    assert result["checks"]["historical_paper_trading_read_only_input"] is True
    assert result["checks"]["historical_paper_trading_no_real_order"] is True
    assert result["checks"]["historical_paper_trading_no_real_order_intent"] is True
    assert result["checks"]["historical_paper_trading_no_broker_api"] is True
    assert result["checks"]["historical_paper_trading_no_account_api"] is True
    assert result["checks"]["historical_paper_trading_no_order_api"] is True
    assert result["checks"]["historical_paper_trading_no_kiwoom_api"] is True
    assert result["checks"]["historical_paper_trading_no_ls_api"] is True
    assert result["checks"]["historical_paper_trading_no_broker_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_kiwoom_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_ls_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_live_trading"] is True
    assert result["checks"]["historical_paper_trading_no_live_prod"] is True
    assert result["checks"]["historical_paper_trading_no_network"] is True
    assert result["checks"]["historical_paper_trading_no_provider_api"] is True
    assert result["checks"]["historical_paper_trading_no_cloud_llm"] is True
    assert result["checks"]["historical_paper_trading_no_local_llm_runtime"] is True
    assert result["checks"]["historical_paper_trading_no_external_execution"] is True
    assert result["checks"]["historical_paper_trading_parquet_unsupported"] is True
    assert result["checks"]["broker_mock_adapter_boundary_fixture_run"] is True
    assert result["checks"]["broker_mock_adapter_boundary_run_generated"] is True
    assert result["checks"]["broker_mock_adapter_capability_report_generated"] is True
    assert result["checks"]["broker_mock_adapter_order_intent_generated"] is True
    assert result["checks"]["broker_mock_adapter_order_request_generated"] is True
    assert result["checks"]["broker_mock_adapter_order_response_generated"] is True
    assert result["checks"]["broker_mock_adapter_execution_report_generated"] is True
    assert result["checks"]["broker_mock_adapter_account_snapshot_generated"] is True
    assert result["checks"]["broker_mock_adapter_position_snapshot_generated"] is True
    assert result["checks"]["broker_mock_adapter_safety_report_generated"] is True
    assert result["checks"]["broker_mock_adapter_gap_report_generated"] is True
    assert result["checks"]["broker_mock_adapter_audit_record_generated"] is True
    assert result["checks"]["broker_mock_adapter_mock_only"] is True
    assert result["checks"]["broker_mock_adapter_paper_only"] is True
    assert result["checks"]["broker_mock_adapter_disabled_by_default"] is True
    assert result["checks"]["broker_mock_adapter_explicit_opt_in_required"] is True
    assert result["checks"]["broker_mock_adapter_non_executable_by_default"] is True
    assert result["checks"]["broker_mock_adapter_local_only"] is True
    assert result["checks"]["broker_mock_adapter_offline_only"] is True
    assert result["checks"]["broker_mock_adapter_no_real_order"] is True
    assert result["checks"]["broker_mock_adapter_no_real_order_intent"] is True
    assert result["checks"]["broker_mock_adapter_no_real_account_mutation"] is True
    assert result["checks"]["broker_mock_adapter_no_live_trading"] is True
    assert result["checks"]["broker_mock_adapter_no_live_prod"] is True
    assert result["checks"]["broker_mock_adapter_no_production_broker"] is True
    assert result["checks"]["broker_mock_adapter_no_credentials_loaded"] is True
    assert result["checks"]["broker_mock_adapter_no_network_call"] is True
    assert result["checks"]["broker_mock_adapter_no_kiwoom_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_ls_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_broker_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_order_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_account_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_provider_api_call"] is True
    assert result["checks"]["broker_mock_adapter_no_websocket_connection"] is True
    assert result["checks"]["broker_mock_adapter_no_cloud_llm"] is True
    assert result["checks"]["broker_mock_adapter_no_local_llm_runtime"] is True
    assert result["checks"]["broker_mock_adapter_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_adapter_draft_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_adapter_draft_build_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_order_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_request_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_response_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_execution_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_account_snapshot_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_position_snapshot_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_adapter_kiwoom_mock_only"] is True
    assert result["checks"]["kiwoom_mock_adapter_draft_only"] is True
    assert result["checks"]["kiwoom_mock_adapter_paper_only"] is True
    assert result["checks"]["kiwoom_mock_adapter_disabled_by_default"] is True
    assert result["checks"]["kiwoom_mock_adapter_explicit_opt_in_required"] is True
    assert result["checks"]["kiwoom_mock_adapter_non_executable"] is True
    assert result["checks"]["kiwoom_mock_adapter_local_only"] is True
    assert result["checks"]["kiwoom_mock_adapter_offline_only"] is True
    assert result["checks"]["kiwoom_mock_adapter_evidence_backed"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_credentials_loaded"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_oauth_token_request"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_api_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_mockapi_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_network_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_websocket_connection"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_real_order"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_real_account_mutation"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_live_trading"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_broker_api_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_order_api_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_account_api_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_provider_api_call"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_cloud_llm"] is True
    assert result["checks"]["kiwoom_mock_adapter_no_local_llm_runtime"] is True
    assert result["checks"]["kiwoom_mock_adapter_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_credential_boundary_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_credential_boundary_check_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_domain_policy_report_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_opt_in_report_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_credential_mock_only"] is True
    assert result["checks"]["kiwoom_mock_credential_boundary_only"] is True
    assert result["checks"]["kiwoom_mock_credential_disabled_by_default"] is True
    assert result["checks"]["kiwoom_mock_credential_explicit_opt_in_required"] is True
    assert result["checks"]["kiwoom_mock_credential_local_only"] is True
    assert result["checks"]["kiwoom_mock_credential_offline_only"] is True
    assert result["checks"]["kiwoom_mock_credential_non_executable"] is True
    assert result["checks"]["kiwoom_mock_credential_no_credentials_loaded"] is True
    assert result["checks"]["kiwoom_mock_credential_no_environment_read"] is True
    assert result["checks"]["kiwoom_mock_credential_no_credential_file_read"] is True
    assert result["checks"]["kiwoom_mock_credential_no_token_issued"] is True
    assert result["checks"]["kiwoom_mock_credential_no_token_revoked"] is True
    assert result["checks"]["kiwoom_mock_credential_no_api_call"] is True
    assert result["checks"]["kiwoom_mock_credential_no_mockapi_call"] is True
    assert result["checks"]["kiwoom_mock_credential_no_websocket_connection"] is True
    assert result["checks"]["kiwoom_mock_credential_no_network_call"] is True
    assert result["checks"]["kiwoom_mock_credential_no_real_order"] is True
    assert result["checks"]["kiwoom_mock_credential_no_live_trading"] is True
    assert result["checks"]["kiwoom_mock_credential_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_credential_no_account_mutation"] is True
    assert result["checks"]["kiwoom_mock_credential_no_production_domain_execution"] is True
    assert result["checks"]["kiwoom_mock_credential_no_cloud_llm"] is True
    assert result["checks"]["kiwoom_mock_credential_no_local_llm_runtime"] is True
    assert result["checks"]["kiwoom_mock_credential_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_oauth_draft_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_oauth_token_request_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_token_response_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_token_revoke_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_token_lifecycle_report_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_mock_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_draft_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_credential_boundary_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_disabled_by_default"] is True
    assert result["checks"]["kiwoom_mock_oauth_explicit_opt_in_required"] is True
    assert result["checks"]["kiwoom_mock_oauth_local_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_offline_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_non_executable"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_credentials_loaded"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_env_read"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_token_issued"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_token_revoked"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_api_call"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_mockapi_call"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_websocket_connection"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_network_call"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_real_order"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_live_trading"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_account_mutation"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_production_domain_execution"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_cloud_llm"] is True
    assert result["checks"]["kiwoom_mock_oauth_no_local_llm_runtime"] is True
    assert result["checks"]["kiwoom_mock_oauth_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_request_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_revoke_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_mock_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_local_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_redacted_output_only"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_raw_secret_token_output"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_token_persistence"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_real_network_in_smoke"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_production_path"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_account_path"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_order_path"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_quote_path"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_websocket_path"] is True
    assert result["checks"]["kiwoom_mock_oauth_execution_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_api_transport_draft_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_api_transport_request_envelope_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_api_transport_policy_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_retry_timeout_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_error_response_draft_generated"] is True
    assert result["checks"]["kiwoom_mock_api_transport_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_transport_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_transport_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_api_transport_draft_only"] is True
    assert result["checks"]["kiwoom_mock_api_transport_mock_only"] is True
    assert result["checks"]["kiwoom_mock_api_transport_offline_only"] is True
    assert result["checks"]["kiwoom_mock_api_transport_local_only"] is True
    assert result["checks"]["kiwoom_mock_api_transport_request_envelope_only"] is True
    assert result["checks"]["kiwoom_mock_api_transport_non_executable"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_authorization_header"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_token_loading"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_token_usage"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_token_refresh"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_environment_read"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_credential_file_read"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_credentials_loaded"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_http_client"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_http_session"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_transport"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_api_call"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_mockapi_call"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_websocket_connection"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_network_call"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_account_read"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_account_mutation"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_real_order"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_live_trading"] is True
    assert result["checks"]["kiwoom_mock_api_transport_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_api_transport_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_check_generated"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_readiness_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_local_only"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_offline_only"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_non_executable"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_quote_draft_ready"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_gap_status_supported"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_oauth_blocked"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_account_blocked"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_order_blocked"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_websocket_blocked"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_unknown_rejected"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_prod_blocked_or_rejected"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_token_loading"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_token_usage"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_token_refresh"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_authorization_header"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_http_client"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_http_session"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_transport"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_api_call"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_mockapi_call"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_websocket_connection"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_network_call"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_account_read"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_account_mutation"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_real_order"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_live_trading"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_no_live_prod"] is True
    assert result["checks"]["kiwoom_mock_api_preflight_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_fixture_run"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_request_generated"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_response_report_generated"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_safety_report_generated"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_gap_report_generated"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_audit_record_generated"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_mock_only"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_local_only"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_read_only_market_data_only"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_redacted_output_only"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_raw_secret_token_output"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_token_persistence"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_token_refresh"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_real_network_in_smoke"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_production_path"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_account_path"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_order_path"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_websocket_path"] is True
    assert result["checks"]["kiwoom_mock_market_data_execution_no_live_prod"] is True
    assert result["checks"]["quant_strategy_robustness_fixture_run"] is True
    assert result["checks"]["quant_strategy_robustness_report_generated"] is True
    assert result["checks"]["quant_strategy_survivorship_bias_report_generated"] is True
    assert result["checks"]["quant_strategy_point_in_time_report_generated"] is True
    assert result["checks"]["quant_strategy_walk_forward_report_generated"] is True
    assert result["checks"]["quant_strategy_data_snooping_report_generated"] is True
    assert result["checks"]["quant_strategy_diversification_report_generated"] is True
    assert result["checks"]["quant_strategy_regime_readiness_report_generated"] is True
    assert result["checks"]["quant_strategy_robustness_local_only"] is True
    assert result["checks"]["quant_strategy_robustness_offline_only"] is True
    assert result["checks"]["quant_strategy_robustness_report_only"] is True
    assert result["checks"]["quant_strategy_robustness_non_executable"] is True
    assert result["checks"]["quant_strategy_robustness_training_ready"] is True
    assert result["checks"]["quant_strategy_robustness_no_live_path"] is True
    assert result["checks"]["quant_strategy_robustness_no_order_path"] is True
    assert result["checks"]["quant_strategy_robustness_no_account_mutation"] is True
    assert result["checks"]["quant_strategy_robustness_no_network"] is True
    assert result["checks"]["quant_strategy_robustness_parquet_unsupported"] is True
    assert result["checks"]["point_in_time_universe_fixture_run"] is True
    assert result["checks"]["point_in_time_universe_report_generated"] is True
    assert result["checks"]["survivorship_bias_dataset_report_generated"] is True
    assert result["checks"]["security_lifecycle_coverage_report_generated"] is True
    assert result["checks"]["dataset_leakage_report_generated"] is True
    assert result["checks"]["dataset_promotion_readiness_report_generated"] is True
    assert result["checks"]["point_in_time_universe_local_only"] is True
    assert result["checks"]["point_in_time_universe_offline_only"] is True
    assert result["checks"]["point_in_time_universe_report_only"] is True
    assert result["checks"]["point_in_time_universe_non_executable"] is True
    assert result["checks"]["point_in_time_universe_training_ready"] is True
    assert result["checks"]["point_in_time_universe_no_live_path"] is True
    assert result["checks"]["point_in_time_universe_no_order_path"] is True
    assert result["checks"]["point_in_time_universe_no_account_mutation"] is True
    assert result["checks"]["point_in_time_universe_no_network"] is True
    assert result["checks"]["point_in_time_universe_parquet_unsupported"] is True
    assert result["checks"]["walk_forward_validation_fixture_run"] is True
    assert result["checks"]["walk_forward_split_report_generated"] is True
    assert result["checks"]["walk_forward_data_snooping_report_generated"] is True
    assert result["checks"]["walk_forward_experiment_lineage_report_generated"] is True
    assert result["checks"]["walk_forward_parameter_search_pressure_report_generated"] is True
    assert result["checks"]["walk_forward_final_test_contamination_report_generated"] is True
    assert result["checks"]["walk_forward_stability_report_generated"] is True
    assert result["checks"]["walk_forward_promotion_readiness_report_generated"] is True
    assert result["checks"]["walk_forward_validation_local_only"] is True
    assert result["checks"]["walk_forward_validation_offline_only"] is True
    assert result["checks"]["walk_forward_validation_report_only"] is True
    assert result["checks"]["walk_forward_validation_non_executable"] is True
    assert result["checks"]["walk_forward_validation_ready_for_validation_or_paper"] is True
    assert result["checks"]["walk_forward_validation_no_live_path"] is True
    assert result["checks"]["walk_forward_validation_no_order_path"] is True
    assert result["checks"]["walk_forward_validation_no_account_mutation"] is True
    assert result["checks"]["walk_forward_validation_no_network"] is True
    assert result["checks"]["walk_forward_validation_parquet_unsupported"] is True
    assert result["checks"]["training_pipeline_promotion_fixture_run"] is True
    assert result["checks"]["training_dataset_eligibility_report_generated"] is True
    assert result["checks"]["training_dependency_report_generated"] is True
    assert result["checks"]["training_leakage_overfit_risk_report_generated"] is True
    assert result["checks"]["training_reproducibility_report_generated"] is True
    assert result["checks"]["training_model_artifact_policy_report_generated"] is True
    assert result["checks"]["training_model_promotion_readiness_report_generated"] is True
    assert result["checks"]["training_pipeline_promotion_local_only"] is True
    assert result["checks"]["training_pipeline_promotion_offline_only"] is True
    assert result["checks"]["training_pipeline_promotion_report_only"] is True
    assert result["checks"]["training_pipeline_promotion_non_executable"] is True
    assert result["checks"]["training_pipeline_promotion_training_ready_or_paper_candidate"] is True
    assert result["checks"]["training_pipeline_promotion_no_live_path"] is True
    assert result["checks"]["training_pipeline_promotion_no_order_path"] is True
    assert result["checks"]["training_pipeline_promotion_no_account_mutation"] is True
    assert result["checks"]["training_pipeline_promotion_no_network"] is True
    assert result["checks"]["training_pipeline_promotion_parquet_unsupported"] is True
    assert result["checks"]["strategy_ensemble_alpha_fixture_run"] is True
    assert result["checks"]["alpha_candidate_report_generated"] is True
    assert result["checks"]["strategy_family_diversification_report_generated"] is True
    assert result["checks"]["alpha_correlation_risk_report_generated"] is True
    assert result["checks"]["drawdown_co_movement_report_generated"] is True
    assert result["checks"]["regime_overlap_report_generated"] is True
    assert result["checks"]["alpha_portfolio_concentration_report_generated"] is True
    assert result["checks"]["ensemble_promotion_readiness_report_generated"] is True
    assert result["checks"]["strategy_ensemble_alpha_local_only"] is True
    assert result["checks"]["strategy_ensemble_alpha_offline_only"] is True
    assert result["checks"]["strategy_ensemble_alpha_report_only"] is True
    assert result["checks"]["strategy_ensemble_alpha_non_executable"] is True
    assert result["checks"]["strategy_ensemble_alpha_ensemble_ready_or_paper_candidate"] is True
    assert result["checks"]["strategy_ensemble_alpha_no_live_path"] is True
    assert result["checks"]["strategy_ensemble_alpha_no_order_path"] is True
    assert result["checks"]["strategy_ensemble_alpha_no_account_mutation"] is True
    assert result["checks"]["strategy_ensemble_alpha_no_network"] is True
    assert result["checks"]["strategy_ensemble_alpha_parquet_unsupported"] is True
    assert result["checks"]["regime_allocation_learning_fixture_run"] is True
    assert result["checks"]["regime_feature_report_generated"] is True
    assert result["checks"]["allocation_action_candidate_report_generated"] is True
    assert result["checks"]["hedge_inverse_eligibility_report_generated"] is True
    assert result["checks"]["forward_outcome_label_report_generated"] is True
    assert result["checks"]["allocation_reward_scoring_report_generated"] is True
    assert result["checks"]["regime_allocation_leakage_report_generated"] is True
    assert result["checks"]["regime_allocation_dataset_readiness_report_generated"] is True
    assert result["checks"]["regime_allocation_learning_local_only"] is True
    assert result["checks"]["regime_allocation_learning_offline_only"] is True
    assert result["checks"]["regime_allocation_learning_report_only"] is True
    assert result["checks"]["regime_allocation_learning_non_executable"] is True
    assert result["checks"]["regime_allocation_learning_training_ready"] is True
    assert result["checks"]["regime_allocation_learning_no_live_path"] is True
    assert result["checks"]["regime_allocation_learning_no_order_path"] is True
    assert result["checks"]["regime_allocation_learning_no_account_mutation"] is True
    assert result["checks"]["regime_allocation_learning_no_network"] is True
    assert result["checks"]["regime_allocation_learning_hedge_inverse_report_only"] is True
    assert result["checks"]["regime_allocation_learning_parquet_unsupported"] is True
    assert result["checks"]["allocation_policy_training_fixture_run"] is True
    assert result["checks"]["allocation_policy_training_summary_report_generated"] is True
    assert result["checks"]["regime_action_selection_report_generated"] is True
    assert result["checks"]["allocation_policy_walk_forward_report_generated"] is True
    assert result["checks"]["allocation_policy_risk_adjusted_report_generated"] is True
    assert result["checks"]["allocation_policy_turnover_slippage_report_generated"] is True
    assert result["checks"]["allocation_policy_drawdown_stability_report_generated"] is True
    assert result["checks"]["allocation_policy_promotion_readiness_report_generated"] is True
    assert result["checks"]["allocation_policy_artifact_report_generated"] is True
    assert result["checks"]["allocation_policy_training_local_only"] is True
    assert result["checks"]["allocation_policy_training_offline_only"] is True
    assert result["checks"]["allocation_policy_training_report_only"] is True
    assert result["checks"]["allocation_policy_training_non_executable"] is True
    assert result["checks"]["allocation_policy_training_trained_or_paper_candidate"] is True
    assert result["checks"]["allocation_policy_training_no_live_path"] is True
    assert result["checks"]["allocation_policy_training_no_order_path"] is True
    assert result["checks"]["allocation_policy_training_no_account_mutation"] is True
    assert result["checks"]["allocation_policy_training_no_network"] is True
    assert result["checks"]["allocation_policy_training_artifact_local_only"] is True
    assert result["checks"]["allocation_policy_training_parquet_unsupported"] is True
    assert result["checks"]["cnn_fear_greed_fixture_run"] is True
    assert result["checks"]["cnn_fear_greed_snapshot_generated"] is True
    assert result["checks"]["cnn_fear_greed_history_report_generated"] is True
    assert result["checks"]["cnn_fear_greed_feature_integration_report_generated"] is True
    assert result["checks"]["cnn_fear_greed_source_health_report_generated"] is True
    assert result["checks"]["cnn_fear_greed_audit_report_generated"] is True
    assert result["checks"]["cnn_fear_greed_safe_default_dry_run"] is True
    assert result["checks"]["cnn_fear_greed_mocked_transport_default"] is True
    assert result["checks"]["cnn_fear_greed_real_network_opt_in_required"] is True
    assert result["checks"]["cnn_fear_greed_no_real_network_called"] is True
    assert result["checks"]["cnn_fear_greed_no_trading_order_account_broker_path"] is True
    assert result["checks"]["cnn_fear_greed_parquet_unsupported"] is True
    assert result["checks"]["risk_adjusted_paper_eval_fixture_run"] is True
    assert result["checks"]["risk_adjusted_paper_eval_summary_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_virtual_portfolio_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_trade_ledger_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_cost_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_risk_adjusted_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_drawdown_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_bucket_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_readiness_report_generated"] is True
    assert result["checks"]["risk_adjusted_paper_eval_local_only"] is True
    assert result["checks"]["risk_adjusted_paper_eval_offline_only"] is True
    assert result["checks"]["risk_adjusted_paper_eval_report_only"] is True
    assert result["checks"]["risk_adjusted_paper_eval_non_executable"] is True
    assert result["checks"]["risk_adjusted_paper_eval_no_live_path"] is True
    assert result["checks"]["risk_adjusted_paper_eval_no_order_path"] is True
    assert result["checks"]["risk_adjusted_paper_eval_no_account_mutation"] is True
    assert result["checks"]["risk_adjusted_paper_eval_no_network"] is True
    assert result["checks"]["risk_adjusted_paper_eval_paper_evaluated_or_pass"] is True
    assert result["checks"]["risk_adjusted_paper_eval_fear_feature_used"] is True
    assert result["checks"]["risk_adjusted_paper_eval_parquet_unsupported"] is True
    assert result["checks"]["controlled_mock_readiness_fixture_run"] is True
    assert result["checks"]["controlled_mock_readiness_summary_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_dependency_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_paper_pass_evidence_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_infrastructure_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_safety_policy_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_boundary_violation_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_gap_report_generated"] is True
    assert result["checks"]["controlled_mock_readiness_local_only"] is True
    assert result["checks"]["controlled_mock_readiness_offline_only"] is True
    assert result["checks"]["controlled_mock_readiness_report_only"] is True
    assert result["checks"]["controlled_mock_readiness_non_executable"] is True
    assert result["checks"]["controlled_mock_readiness_no_live_path"] is True
    assert result["checks"]["controlled_mock_readiness_no_order_path"] is True
    assert result["checks"]["controlled_mock_readiness_no_account_mutation"] is True
    assert result["checks"]["controlled_mock_readiness_no_network"] is True
    assert result["checks"]["controlled_mock_readiness_no_mock_order_execution"] is True
    assert result["checks"]["controlled_mock_readiness_review_only"] is True
    assert result["checks"]["controlled_mock_readiness_parquet_unsupported"] is True
    assert result["checks"]["controlled_mock_dry_run_fixture_run"] is True
    assert result["checks"]["controlled_mock_dry_run_summary_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_preview_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_preflight_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_provider_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_market_regime_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_position_sizing_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_event_risk_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_breadth_routing_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_order_gate_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_risk_budget_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_kill_switch_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_rollback_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_audit_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_boundary_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_gap_report_generated"] is True
    assert result["checks"]["controlled_mock_dry_run_report_only"] is True
    assert result["checks"]["controlled_mock_dry_run_non_executable"] is True
    assert result["checks"]["controlled_mock_dry_run_local_only"] is True
    assert result["checks"]["controlled_mock_dry_run_offline_only"] is True
    assert result["checks"]["controlled_mock_dry_run_no_live_order_account_prod_path"] is True
    assert result["checks"]["controlled_mock_dry_run_no_real_broker_kiwoom_network_provider_call"] is True
    assert result["checks"]["controlled_mock_dry_run_no_mock_order_execution"] is True
    assert result["checks"]["controlled_mock_dry_run_preview_non_executable"] is True
    assert result["checks"]["controlled_mock_dry_run_execution_review_or_rehearsed_only"] is True
    assert result["checks"]["controlled_mock_dry_run_parquet_unsupported"] is True
    assert result["checks"]["read_only_provider_adapter_fixture_run"] is True
    assert result["checks"]["read_only_provider_adapter_summary_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_evidence_map_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_ls_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_canonical_contract_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_capability_matrix_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_blocked_api_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_migration_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_gap_report_generated"] is True
    assert result["checks"]["read_only_provider_adapter_local_only"] is True
    assert result["checks"]["read_only_provider_adapter_offline_only"] is True
    assert result["checks"]["read_only_provider_adapter_report_only"] is True
    assert result["checks"]["read_only_provider_adapter_non_executable"] is True
    assert result["checks"]["read_only_provider_adapter_no_provider_network_call"] is True
    assert result["checks"]["read_only_provider_adapter_no_credential_env_read"] is True
    assert result["checks"]["read_only_provider_adapter_no_auth_header_generation"] is True
    assert result["checks"]["read_only_provider_adapter_account_order_blocked"] is True
    assert result["checks"]["read_only_provider_adapter_canonical_output_only"] is True
    assert result["checks"]["read_only_provider_adapter_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_fixture_run"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_request_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_mocked_response_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_canonical_ohlcv_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_continuation_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_safety_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_integration_compatibility_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_gap_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_local_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_offline_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_report_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_non_executable"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_network"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_provider_api"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_account_order_path"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_token_loading"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_canonical_ohlcv_output_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_chart_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_fixture_run"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_request_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_mocked_response_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_canonical_rank_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_canonical_outlier_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_continuation_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_safety_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_v7_integration_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_gap_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_local_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_offline_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_report_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_non_executable"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_network"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_provider_api"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_account_order_path"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_token_loading"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_canonical_output_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_rank_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_fixture_run"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_request_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_mocked_response_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_canonical_quote_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_canonical_orderbook_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_liquidity_hint_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_basic_info_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_continuation_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_safety_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_v7_integration_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_gap_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_local_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_offline_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_report_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_non_executable"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_network"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_provider_api"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_account_order_path"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_token_loading"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_canonical_output_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_quote_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_fixture_run"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_request_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_mocked_response_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_canonical_investor_flow_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_canonical_program_flow_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_short_lending_capability_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_capability_matrix_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_continuation_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_safety_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_v7_integration_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_gap_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_local_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_offline_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_report_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_non_executable"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_network"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_provider_api"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_account_order_path"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_token_loading"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_canonical_output_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_flow_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_fixture_run"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_request_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_mocked_response_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_canonical_theme_leadership_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_canonical_theme_membership_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_canonical_etf_trend_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_capability_matrix_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_continuation_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_safety_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_v7_integration_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_gap_report_generated"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_local_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_offline_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_report_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_non_executable"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_network"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_provider_api"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_account_order_path"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_token_loading"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_canonical_output_only"] is True
    assert result["checks"]["kiwoom_rest_readonly_sector_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_fixture_run"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_summary_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_source_coverage_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_freshness_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_completeness_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_conflict_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_domestic_stock_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_v710_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_v712_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_v713_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_safety_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_gap_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_local_only"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_offline_only"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_report_only"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_non_executable"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_network"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_provider_api"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_account_order_path"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_token_loading"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_canonical_output_only"] is True
    assert result["checks"]["kiwoom_readonly_snapshot_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_manual_response_import_fixture_run"] is True
    assert result["checks"]["kiwoom_manual_response_import_summary_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_file_classification_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_sensitive_scan_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_routing_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_canonical_output_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_snapshot_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_safety_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_gap_report_generated"] is True
    assert result["checks"]["kiwoom_manual_response_import_local_only"] is True
    assert result["checks"]["kiwoom_manual_response_import_offline_only"] is True
    assert result["checks"]["kiwoom_manual_response_import_report_only"] is True
    assert result["checks"]["kiwoom_manual_response_import_non_executable"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_network"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_provider_api"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_account_order_path"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_token_loading"] is True
    assert result["checks"]["kiwoom_manual_response_import_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_manual_response_import_canonical_output_only"] is True
    assert result["checks"]["kiwoom_manual_response_import_snapshot_composed"] is True
    assert result["checks"]["kiwoom_manual_response_import_snapshot_not_empty"] is True
    assert result["checks"]["kiwoom_manual_response_import_parquet_unsupported"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_fixture_run"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_summary_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_request_preview_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_allowlist_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_token_provider_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_capture_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_response_routing_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_snapshot_validation_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_readiness_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_safety_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_gap_report_generated"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_local_only"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_offline_only"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_report_only"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_non_executable"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_network"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_provider_api"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_account_order_path"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_env_credential_read"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_token_loading"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_no_auth_header_generation"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_canonical_output_only"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_snapshot_validation_ran"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_real_network_not_used"] is True
    assert result["checks"]["kiwoom_readonly_final_transport_parquet_unsupported"] is True
    assert result["checks"]["market_regime_fixture_run"] is True
    assert result["checks"]["market_regime_summary_report_generated"] is True
    assert result["checks"]["market_regime_input_snapshot_report_generated"] is True
    assert result["checks"]["market_regime_risk_appetite_report_generated"] is True
    assert result["checks"]["market_regime_direction_report_generated"] is True
    assert result["checks"]["market_regime_volatility_report_generated"] is True
    assert result["checks"]["market_regime_stress_report_generated"] is True
    assert result["checks"]["market_regime_conflict_report_generated"] is True
    assert result["checks"]["market_regime_constraint_report_generated"] is True
    assert result["checks"]["market_regime_training_feature_report_generated"] is True
    assert result["checks"]["market_regime_gap_report_generated"] is True
    assert result["checks"]["market_regime_local_only"] is True
    assert result["checks"]["market_regime_offline_only"] is True
    assert result["checks"]["market_regime_report_only"] is True
    assert result["checks"]["market_regime_non_executable"] is True
    assert result["checks"]["market_regime_no_live_path"] is True
    assert result["checks"]["market_regime_no_order_path"] is True
    assert result["checks"]["market_regime_no_account_mutation"] is True
    assert result["checks"]["market_regime_no_network"] is True
    assert result["checks"]["market_regime_training_feature_ready"] is True
    assert result["checks"]["market_regime_parquet_unsupported"] is True
    assert result["checks"]["macro_regime_fixture_run"] is True
    assert result["checks"]["macro_regime_snapshot_generated"] is True
    assert result["checks"]["macro_regime_classification_generated"] is True
    assert result["checks"]["macro_regime_provider_capability_report_generated"] is True
    assert result["checks"]["macro_regime_freshness_report_generated"] is True
    assert result["checks"]["macro_regime_conflict_report_generated"] is True
    assert result["checks"]["macro_regime_event_window_report_generated"] is True
    assert result["checks"]["macro_regime_v7_integration_report_generated"] is True
    assert result["checks"]["macro_regime_v8_integration_report_generated"] is True
    assert result["checks"]["macro_regime_report_only"] is True
    assert result["checks"]["macro_regime_no_network"] is True
    assert result["checks"]["macro_regime_no_env_read"] is True
    assert result["checks"]["macro_regime_no_account_order_path"] is True
    assert result["checks"]["macro_regime_no_executable_output"] is True
    assert result["checks"]["macro_regime_boundary_only"] is True
    assert result["checks"]["macro_regime_parquet_unsupported"] is True
    assert result["checks"]["feature_store_fixture_run"] is True
    assert result["checks"]["feature_store_cache_manifest_generated"] is True
    assert result["checks"]["feature_store_dataset_manifest_generated"] is True
    assert result["checks"]["feature_store_training_dataset_manifest_generated"] is True
    assert result["checks"]["feature_store_walk_forward_plan_generated"] is True
    assert result["checks"]["feature_store_leakage_report_generated"] is True
    assert result["checks"]["feature_store_backend_capability_report_generated"] is True
    assert result["checks"]["feature_store_v7_integration_report_generated"] is True
    assert result["checks"]["feature_store_v8_integration_report_generated"] is True
    assert result["checks"]["feature_store_v9_integration_report_generated"] is True
    assert result["checks"]["feature_store_report_only"] is True
    assert result["checks"]["feature_store_no_network"] is True
    assert result["checks"]["feature_store_no_env_read"] is True
    assert result["checks"]["feature_store_no_account_order_path"] is True
    assert result["checks"]["feature_store_no_training"] is True
    assert result["checks"]["feature_store_no_paper_trading"] is True
    assert result["checks"]["feature_store_safe_local_materialization_only"] is True
    assert result["checks"]["paper_evaluation_fixture_run"] is True
    assert result["checks"]["paper_evaluation_plan_generated"] is True
    assert result["checks"]["paper_evaluation_signal_replay_generated"] is True
    assert result["checks"]["paper_evaluation_fill_simulation_generated"] is True
    assert result["checks"]["paper_evaluation_ledger_generated"] is True
    assert result["checks"]["paper_evaluation_metrics_generated"] is True
    assert result["checks"]["paper_evaluation_integration_generated"] is True
    assert result["checks"]["paper_evaluation_safety_generated"] is True
    assert result["checks"]["paper_evaluation_report_only"] is True
    assert result["checks"]["paper_evaluation_no_network"] is True
    assert result["checks"]["paper_evaluation_no_env_read"] is True
    assert result["checks"]["paper_evaluation_no_account_order_path"] is True
    assert result["checks"]["paper_evaluation_no_model_training"] is True
    assert result["checks"]["paper_evaluation_no_broker_paper_api"] is True
    assert result["checks"]["paper_evaluation_no_executable_output"] is True
    assert result["checks"]["portfolio_reconciliation_fixture_run"] is True
    assert result["checks"]["portfolio_reconciliation_plan_generated"] is True
    assert result["checks"]["portfolio_reconciliation_report_generated"] is True
    assert result["checks"]["portfolio_reconciliation_integration_generated"] is True
    assert result["checks"]["portfolio_reconciliation_report_only"] is True
    assert result["checks"]["portfolio_reconciliation_no_network"] is True
    assert result["checks"]["portfolio_reconciliation_no_env_read"] is True
    assert result["checks"]["portfolio_reconciliation_no_account_order_path"] is True
    assert result["checks"]["portfolio_reconciliation_no_executable_output"] is True
    assert result["checks"]["portfolio_reconciliation_redacted_account_ref"] is True
    assert result["checks"]["market_data_provider_registry_fixture_run"] is True
    assert result["checks"]["market_data_provider_registry_report_generated"] is True
    assert result["checks"]["market_data_provider_module_requirement_report_generated"] is True
    assert result["checks"]["market_data_provider_readiness_matrix_report_generated"] is True
    assert result["checks"]["market_data_provider_canonical_contract_report_generated"] is True
    assert result["checks"]["market_data_provider_symbol_mapping_report_generated"] is True
    assert result["checks"]["market_data_provider_selection_report_generated"] is True
    assert result["checks"]["market_data_provider_gap_report_generated"] is True
    assert result["checks"]["market_data_provider_local_only"] is True
    assert result["checks"]["market_data_provider_offline_only"] is True
    assert result["checks"]["market_data_provider_report_only"] is True
    assert result["checks"]["market_data_provider_non_executable"] is True
    assert result["checks"]["market_data_provider_no_live_path"] is True
    assert result["checks"]["market_data_provider_no_order_path"] is True
    assert result["checks"]["market_data_provider_no_account_mutation"] is True
    assert result["checks"]["market_data_provider_no_network"] is True
    assert result["checks"]["market_data_provider_no_provider_call"] is True
    assert result["checks"]["market_data_provider_parquet_unsupported"] is True
    assert result["checks"]["position_sizing_fixture_run"] is True
    assert result["checks"]["position_sizing_summary_report_generated"] is True
    assert result["checks"]["position_sizing_stop_distance_report_generated"] is True
    assert result["checks"]["position_sizing_risk_budget_report_generated"] is True
    assert result["checks"]["position_sizing_data_readiness_report_generated"] is True
    assert result["checks"]["position_sizing_quantity_notional_report_generated"] is True
    assert result["checks"]["position_sizing_cost_assumption_report_generated"] is True
    assert result["checks"]["position_sizing_market_regime_adjustment_report_generated"] is True
    assert result["checks"]["position_sizing_inverse_hedge_report_generated"] is True
    assert result["checks"]["position_sizing_boundary_report_generated"] is True
    assert result["checks"]["position_sizing_gap_report_generated"] is True
    assert result["checks"]["position_sizing_local_only"] is True
    assert result["checks"]["position_sizing_offline_only"] is True
    assert result["checks"]["position_sizing_report_only"] is True
    assert result["checks"]["position_sizing_non_executable"] is True
    assert result["checks"]["position_sizing_no_live_path"] is True
    assert result["checks"]["position_sizing_no_order_path"] is True
    assert result["checks"]["position_sizing_no_account_mutation"] is True
    assert result["checks"]["position_sizing_no_network"] is True
    assert result["checks"]["position_sizing_no_provider_call"] is True
    assert result["checks"]["position_sizing_parquet_unsupported"] is True
    assert result["checks"]["event_risk_fixture_run"] is True
    assert result["checks"]["event_risk_summary_report_generated"] is True
    assert result["checks"]["event_risk_calendar_snapshot_report_generated"] is True
    assert result["checks"]["event_risk_event_window_report_generated"] is True
    assert result["checks"]["event_risk_restriction_report_generated"] is True
    assert result["checks"]["event_risk_position_sizing_adjustment_report_generated"] is True
    assert result["checks"]["event_risk_provider_readiness_report_generated"] is True
    assert result["checks"]["event_risk_leakage_report_generated"] is True
    assert result["checks"]["event_risk_gap_report_generated"] is True
    assert result["checks"]["event_risk_local_only"] is True
    assert result["checks"]["event_risk_offline_only"] is True
    assert result["checks"]["event_risk_report_only"] is True
    assert result["checks"]["event_risk_non_executable"] is True
    assert result["checks"]["event_risk_no_live_path"] is True
    assert result["checks"]["event_risk_no_order_path"] is True
    assert result["checks"]["event_risk_no_account_mutation"] is True
    assert result["checks"]["event_risk_no_network"] is True
    assert result["checks"]["event_risk_no_provider_call"] is True
    assert result["checks"]["event_risk_parquet_unsupported"] is True
    assert result["checks"]["breadth_leadership_routing_fixture_run"] is True
    assert result["checks"]["breadth_leadership_summary_report_generated"] is True
    assert result["checks"]["breadth_input_snapshot_report_generated"] is True
    assert result["checks"]["advance_decline_report_generated"] is True
    assert result["checks"]["new_high_low_report_generated"] is True
    assert result["checks"]["up_down_volume_participation_report_generated"] is True
    assert result["checks"]["sector_leadership_report_generated"] is True
    assert result["checks"]["leadership_concentration_report_generated"] is True
    assert result["checks"]["index_distortion_report_generated"] is True
    assert result["checks"]["equal_weight_divergence_report_generated"] is True
    assert result["checks"]["outlier_momentum_candidate_report_generated"] is True
    assert result["checks"]["outlier_sleeve_risk_report_generated"] is True
    assert result["checks"]["breadth_routing_downstream_constraint_report_generated"] is True
    assert result["checks"]["breadth_routing_provider_readiness_report_generated"] is True
    assert result["checks"]["breadth_routing_leakage_report_generated"] is True
    assert result["checks"]["breadth_routing_gap_report_generated"] is True
    assert result["checks"]["breadth_routing_local_only"] is True
    assert result["checks"]["breadth_routing_offline_only"] is True
    assert result["checks"]["breadth_routing_report_only"] is True
    assert result["checks"]["breadth_routing_non_executable"] is True
    assert result["checks"]["breadth_routing_no_live_path"] is True
    assert result["checks"]["breadth_routing_no_order_path"] is True
    assert result["checks"]["breadth_routing_no_account_mutation"] is True
    assert result["checks"]["breadth_routing_no_network"] is True
    assert result["checks"]["breadth_routing_no_provider_call"] is True
    assert result["checks"]["breadth_routing_parquet_unsupported"] is True
    assert result["checks"]["investing_crawler_called"] is False
    assert result["checks"]["finviz_scraper_called"] is False
    assert result["checks"]["news_ingestion_called"] is False
    assert result["checks"]["gemini_called"] is False
    assert result["checks"]["kiwoom_mockapi_called"] is False
    assert result["checks"]["ls_api_called"] is False
    assert result["checks"]["account_api_called"] is False
    assert result["checks"]["order_api_called"] is False
    assert result["checks"]["oauth_token_requested"] is False
    assert result["checks"]["oauth_token_revoked"] is False
    assert result["checks"]["environment_variables_read"] is False
    assert result["checks"]["credential_file_read"] is False
    assert result["checks"]["websocket_connected"] is False
    assert result["checks"]["prompt_pack_fixture_run"] is True
    assert result["checks"]["prompt_pack_validation_run"] is True
    assert result["checks"]["prompt_pack_gap_report_run"] is True
    assert result["checks"]["llm_called"] is False
    assert result["checks"]["real_model_called"] is False
    assert result["checks"]["strategy_track_required"] is True
    assert result["checks"]["market_profile_resolved"] is True
    assert result["checks"]["domestic_kr_only"] is True
    assert result["checks"]["normalized_realtime_event_consumed"] is True
    assert result["checks"]["scanner_candidate_report_generated"] is True
    assert result["checks"]["scanner_candidate_consumed"] is True
    assert result["checks"]["technical_evidence_context_checked"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["candidate_evaluation_report_generated"] is True
    assert result["checks"]["normalized_realtime_event_sequence_consumed"] is True
    assert result["checks"]["scanner_candidate_trace_generated"] is True
    assert result["checks"]["candidate_evaluation_trace_generated"] is True
    assert result["checks"]["replay_metrics_report_generated"] is True
    assert result["checks"]["promotion_readiness_report_generated"] is True
    assert result["checks"]["replay_evaluation_report_consumed"] is True
    assert result["checks"]["single_replay_comparison_generated"] is True
    assert result["checks"]["calibration_pack_aggregated"] is True
    assert result["checks"]["policy_candidate_comparison_generated"] is True
    assert result["checks"]["promotion_gate_report_generated"] is True
    assert result["checks"]["promotion_gate_pack_level_only"] is True
    assert result["checks"]["promotion_gate_report_consumed"] is True
    assert result["checks"]["candidate_evaluation_report_consumed"] is True
    assert result["checks"]["paper_shadow_explicit_opt_in_required"] is True
    assert result["checks"]["paper_shadow_journal_generated"] is True
    assert result["checks"]["paper_shadow_candidate_level_entries"] is True
    assert result["checks"]["paper_shadow_review_report_generated"] is True
    assert result["checks"]["paper_shadow_review_summary_derived_from_entries"] is True
    assert result["checks"]["paper_shadow_non_executable"] is True
    assert result["checks"]["strategy_track_required_for_trading_advisory"] is True
    assert result["checks"]["market_profile_required_for_trading_advisory"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["model_runtime_called"] is False
    assert result["checks"]["cloud_llm_called"] is False
    assert result["checks"]["kiwoom_api_called"] is False
    assert result["checks"]["broker_api_called"] is False
    assert result["checks"]["credentials_accessed"] is False
    assert result["checks"]["cloud_backend_used"] is False
    assert result["checks"]["model_downloaded"] is False
    assert result["checks"]["orders_created"] is False
    assert result["checks"]["order_intent_created"] is False
    assert result["checks"]["order_drafts_created"] is False
    assert result["checks"]["execution_approval_enabled"] is False
    assert result["checks"]["live_or_prod_used"] is False
    assert result["checks"]["strategy_track_comparison_count"] == 1
