from stock_risk_mcp.system_smoke import run_system_smoke


def test_system_smoke_validates_local_workflow(tmp_path) -> None:
    result = run_system_smoke(tmp_path / "smoke.sqlite3", tmp_path / "outputs")

    assert result["status"] in {"COMPLETED", "PARTIAL"}
    assert result["checks"]["db_migration"] is True
    assert result["checks"]["mock_connector_output"] is True
    assert result["checks"]["import"] is True
    assert result["checks"]["pipeline_run"] is True
    assert result["checks"]["dashboard_html"] is True
    assert result["checks"]["external_network_calls"] is False
    assert result["checks"]["strategy_fixture_run"] is True
    assert result["checks"]["strategy_backtest_fixture_run"] is True
    assert result["checks"]["technical_evidence_fixture_run"] is True
    assert result["checks"]["market_discovery_fixture_run"] is True
    assert result["checks"]["llm_feature_store_fixture_run"] is True
    assert result["checks"]["llm_signal_evaluation_fixture_run"] is True
    assert result["checks"]["trade_plan_fixture_run"] is True
    assert result["checks"]["paper_eval_fixture_run"] is True
    assert result["checks"]["policy_replay_fixture_run"] is True
    assert result["checks"]["llm_advisory_fixture_run"] is True
    assert result["checks"]["local_model_runtime_fixture_run"] is True
    assert result["checks"]["local_model_benchmark_fixture_run"] is True
    assert result["checks"]["local_model_decision_report_fixture_run"] is True
    assert result["checks"]["strategy_track_fixture_run"] is True
    assert result["checks"]["market_profit_fixture_run"] is True
    assert result["checks"]["domestic_realtime_fixture_run"] is True
    assert result["checks"]["domestic_scanner_fixture_run"] is True
    assert result["checks"]["domestic_candidate_evaluation_fixture_run"] is True
    assert result["checks"]["domestic_replay_fixture_run"] is True
    assert result["checks"]["domestic_calibration_fixture_run"] is True
    assert result["checks"]["domestic_paper_shadow_fixture_run"] is True
    assert result["checks"]["historical_data_fixture_run"] is True
    assert result["checks"]["historical_manifest_generated"] is True
    assert result["checks"]["historical_calendar_fixture_run"] is True
    assert result["checks"]["historical_calendar_manifest_generated"] is True
    assert result["checks"]["historical_replay_bridge_fixture_run"] is True
    assert result["checks"]["historical_replay_event_stream_generated"] is True
    assert result["checks"]["historical_replay_windows_generated"] is True
    assert result["checks"]["historical_replay_event_context_attached"] is True
    assert result["checks"]["historical_scanner_replay_input_generated"] is True
    assert result["checks"]["calendar_aware_windowing_enabled"] is True
    assert result["checks"]["holiday_sessions_not_counted_as_data_gaps"] is True
    assert result["checks"]["early_close_sessions_flagged"] is True
    assert result["checks"]["event_context_attached_report_only"] is True
    assert result["checks"]["scanner_replay_report_only"] is True
    assert result["checks"]["scanner_replay_non_order_candidate"] is True
    assert result["checks"]["historical_replay_read_only"] is True
    assert result["checks"]["historical_replay_non_executable"] is True
    assert result["checks"]["historical_replay_local_files_only"] is True
    assert result["checks"]["historical_replay_remote_fetch_allowed"] is False
    assert result["checks"]["historical_replay_api_provider_called"] is False
    assert result["checks"]["historical_replay_order_intent_created"] is False
    assert result["checks"]["historical_replay_live_or_prod_used"] is False
    assert result["checks"]["historical_replay_cloud_llm_called"] is False
    assert result["checks"]["historical_replay_model_runtime_called"] is False
    assert result["checks"]["historical_replay_ml_training_run"] is False
    assert result["checks"]["investing_crawler_called"] is False
    assert result["checks"]["finviz_scraper_called"] is False
    assert result["checks"]["news_ingestion_called"] is False
    assert result["checks"]["gemini_called"] is False
    assert result["checks"]["ls_api_called"] is False
    assert result["checks"]["prompt_pack_fixture_run"] is True
    assert result["checks"]["prompt_pack_validation_run"] is True
    assert result["checks"]["prompt_pack_gap_report_run"] is True
    assert result["checks"]["llm_called"] is False
    assert result["checks"]["real_model_called"] is False
    assert result["checks"]["strategy_track_required"] is True
    assert result["checks"]["market_profile_resolved"] is True
    assert result["checks"]["domestic_kr_only"] is True
    assert result["checks"]["normalized_realtime_event_consumed"] is True
    assert result["checks"]["scanner_candidate_report_generated"] is True
    assert result["checks"]["scanner_candidate_consumed"] is True
    assert result["checks"]["technical_evidence_context_checked"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["candidate_evaluation_report_generated"] is True
    assert result["checks"]["normalized_realtime_event_sequence_consumed"] is True
    assert result["checks"]["scanner_candidate_trace_generated"] is True
    assert result["checks"]["candidate_evaluation_trace_generated"] is True
    assert result["checks"]["replay_metrics_report_generated"] is True
    assert result["checks"]["promotion_readiness_report_generated"] is True
    assert result["checks"]["replay_evaluation_report_consumed"] is True
    assert result["checks"]["single_replay_comparison_generated"] is True
    assert result["checks"]["calibration_pack_aggregated"] is True
    assert result["checks"]["policy_candidate_comparison_generated"] is True
    assert result["checks"]["promotion_gate_report_generated"] is True
    assert result["checks"]["promotion_gate_pack_level_only"] is True
    assert result["checks"]["promotion_gate_report_consumed"] is True
    assert result["checks"]["candidate_evaluation_report_consumed"] is True
    assert result["checks"]["paper_shadow_explicit_opt_in_required"] is True
    assert result["checks"]["paper_shadow_journal_generated"] is True
    assert result["checks"]["paper_shadow_candidate_level_entries"] is True
    assert result["checks"]["paper_shadow_review_report_generated"] is True
    assert result["checks"]["paper_shadow_review_summary_derived_from_entries"] is True
    assert result["checks"]["paper_shadow_non_executable"] is True
    assert result["checks"]["strategy_track_required_for_trading_advisory"] is True
    assert result["checks"]["market_profile_required_for_trading_advisory"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["model_runtime_called"] is False
    assert result["checks"]["cloud_llm_called"] is False
    assert result["checks"]["kiwoom_api_called"] is False
    assert result["checks"]["broker_api_called"] is False
    assert result["checks"]["credentials_accessed"] is False
    assert result["checks"]["cloud_backend_used"] is False
    assert result["checks"]["model_downloaded"] is False
    assert result["checks"]["orders_created"] is False
    assert result["checks"]["order_intent_created"] is False
    assert result["checks"]["order_drafts_created"] is False
    assert result["checks"]["execution_approval_enabled"] is False
    assert result["checks"]["live_or_prod_used"] is False
    assert result["checks"]["strategy_track_comparison_count"] == 1
