from stock_risk_mcp.system_smoke import run_system_smoke


def test_system_smoke_validates_local_workflow(tmp_path) -> None:
    result = run_system_smoke(tmp_path / "smoke.sqlite3", tmp_path / "outputs")

    assert result["status"] in {"COMPLETED", "PARTIAL"}
    assert result["checks"]["db_migration"] is True
    assert result["checks"]["mock_connector_output"] is True
    assert result["checks"]["import"] is True
    assert result["checks"]["pipeline_run"] is True
    assert result["checks"]["dashboard_html"] is True
    assert result["checks"]["external_network_calls"] is False
    assert result["checks"]["strategy_fixture_run"] is True
    assert result["checks"]["strategy_backtest_fixture_run"] is True
    assert result["checks"]["technical_evidence_fixture_run"] is True
    assert result["checks"]["market_discovery_fixture_run"] is True
    assert result["checks"]["llm_feature_store_fixture_run"] is True
    assert result["checks"]["llm_signal_evaluation_fixture_run"] is True
    assert result["checks"]["trade_plan_fixture_run"] is True
    assert result["checks"]["paper_eval_fixture_run"] is True
    assert result["checks"]["policy_replay_fixture_run"] is True
    assert result["checks"]["llm_advisory_fixture_run"] is True
    assert result["checks"]["local_model_runtime_fixture_run"] is True
    assert result["checks"]["local_model_benchmark_fixture_run"] is True
    assert result["checks"]["local_model_decision_report_fixture_run"] is True
    assert result["checks"]["strategy_track_fixture_run"] is True
    assert result["checks"]["market_profit_fixture_run"] is True
    assert result["checks"]["domestic_realtime_fixture_run"] is True
    assert result["checks"]["domestic_scanner_fixture_run"] is True
    assert result["checks"]["domestic_candidate_evaluation_fixture_run"] is True
    assert result["checks"]["domestic_replay_fixture_run"] is True
    assert result["checks"]["domestic_calibration_fixture_run"] is True
    assert result["checks"]["domestic_paper_shadow_fixture_run"] is True
    assert result["checks"]["historical_data_fixture_run"] is True
    assert result["checks"]["historical_manifest_generated"] is True
    assert result["checks"]["historical_calendar_fixture_run"] is True
    assert result["checks"]["historical_calendar_manifest_generated"] is True
    assert result["checks"]["historical_replay_bridge_fixture_run"] is True
    assert result["checks"]["historical_replay_event_stream_generated"] is True
    assert result["checks"]["historical_replay_windows_generated"] is True
    assert result["checks"]["historical_replay_event_context_attached"] is True
    assert result["checks"]["historical_scanner_replay_input_generated"] is True
    assert result["checks"]["calendar_aware_windowing_enabled"] is True
    assert result["checks"]["holiday_sessions_not_counted_as_data_gaps"] is True
    assert result["checks"]["early_close_sessions_flagged"] is True
    assert result["checks"]["event_context_attached_report_only"] is True
    assert result["checks"]["scanner_replay_report_only"] is True
    assert result["checks"]["scanner_replay_non_order_candidate"] is True
    assert result["checks"]["historical_replay_read_only"] is True
    assert result["checks"]["historical_replay_non_executable"] is True
    assert result["checks"]["historical_replay_local_files_only"] is True
    assert result["checks"]["historical_replay_remote_fetch_allowed"] is False
    assert result["checks"]["historical_replay_api_provider_called"] is False
    assert result["checks"]["historical_replay_order_intent_created"] is False
    assert result["checks"]["historical_replay_live_or_prod_used"] is False
    assert result["checks"]["historical_replay_cloud_llm_called"] is False
    assert result["checks"]["historical_replay_model_runtime_called"] is False
    assert result["checks"]["historical_replay_ml_training_run"] is False
    assert result["checks"]["historical_outcome_observation_fixture_run"] is True
    assert result["checks"]["historical_outcome_windows_generated"] is True
    assert result["checks"]["historical_outcome_metrics_generated"] is True
    assert result["checks"]["historical_outcome_labels_report_only"] is True
    assert result["checks"]["historical_outcome_no_lookahead_guard_enabled"] is True
    assert result["checks"]["historical_outcome_scanner_input_not_mutated"] is True
    assert result["checks"]["historical_outcome_read_only"] is True
    assert result["checks"]["historical_outcome_non_executable"] is True
    assert result["checks"]["historical_outcome_local_files_only"] is True
    assert result["checks"]["historical_outcome_remote_fetch_allowed"] is False
    assert result["checks"]["historical_outcome_api_provider_called"] is False
    assert result["checks"]["historical_outcome_order_intent_created"] is False
    assert result["checks"]["historical_outcome_live_or_prod_used"] is False
    assert result["checks"]["historical_outcome_cloud_llm_called"] is False
    assert result["checks"]["historical_outcome_model_runtime_called"] is False
    assert result["checks"]["historical_outcome_ml_training_run"] is False
    assert result["checks"]["historical_dataset_assembly_fixture_run"] is True
    assert result["checks"]["historical_dataset_records_generated"] is True
    assert result["checks"]["historical_dataset_feature_outcome_separated"] is True
    assert result["checks"]["historical_dataset_no_lookahead_guard_enabled"] is True
    assert result["checks"]["historical_dataset_scanner_input_not_mutated"] is True
    assert result["checks"]["historical_dataset_report_only"] is True
    assert result["checks"]["historical_dataset_read_only"] is True
    assert result["checks"]["historical_dataset_non_executable"] is True
    assert result["checks"]["historical_dataset_local_files_only"] is True
    assert result["checks"]["historical_dataset_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_api_provider_called"] is False
    assert result["checks"]["historical_dataset_order_intent_created"] is False
    assert result["checks"]["historical_dataset_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_ml_training_run"] is False
    assert result["checks"]["historical_dataset_validation_fixture_run"] is True
    assert result["checks"]["historical_dataset_validation_report_generated"] is True
    assert result["checks"]["historical_dataset_leakage_audit_generated"] is True
    assert result["checks"]["historical_dataset_chronological_split_manifest_generated"] is True
    assert result["checks"]["historical_dataset_feature_outcome_leakage_absent"] is True
    assert result["checks"]["historical_dataset_split_is_chronological"] is True
    assert result["checks"]["historical_dataset_split_no_random_shuffle"] is True
    assert result["checks"]["historical_dataset_split_no_partition_overlap"] is True
    assert result["checks"]["historical_dataset_split_no_duplicate_record_ids"] is True
    assert result["checks"]["historical_dataset_coverage_report_generated"] is True
    assert result["checks"]["historical_dataset_label_distribution_generated"] is True
    assert result["checks"]["historical_dataset_validation_report_only"] is True
    assert result["checks"]["historical_dataset_validation_read_only"] is True
    assert result["checks"]["historical_dataset_validation_non_executable"] is True
    assert result["checks"]["historical_dataset_validation_local_files_only"] is True
    assert result["checks"]["historical_dataset_validation_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_validation_api_provider_called"] is False
    assert result["checks"]["historical_dataset_validation_order_intent_created"] is False
    assert result["checks"]["historical_dataset_validation_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_validation_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_validation_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_validation_ml_training_run"] is False
    assert result["checks"]["historical_dataset_readiness_fixture_run"] is True
    assert result["checks"]["historical_dataset_readiness_report_generated"] is True
    assert result["checks"]["historical_dataset_split_quality_report_generated"] is True
    assert result["checks"]["historical_dataset_imbalance_report_generated"] is True
    assert result["checks"]["historical_dataset_baseline_evaluation_generated"] is True
    assert result["checks"]["historical_dataset_baseline_non_learning"] is True
    assert result["checks"]["historical_dataset_readiness_report_only"] is True
    assert result["checks"]["historical_dataset_readiness_read_only"] is True
    assert result["checks"]["historical_dataset_readiness_non_executable"] is True
    assert result["checks"]["historical_dataset_readiness_local_files_only"] is True
    assert result["checks"]["historical_dataset_readiness_remote_fetch_allowed"] is False
    assert result["checks"]["historical_dataset_readiness_api_provider_called"] is False
    assert result["checks"]["historical_dataset_readiness_order_intent_created"] is False
    assert result["checks"]["historical_dataset_readiness_live_or_prod_used"] is False
    assert result["checks"]["historical_dataset_readiness_cloud_llm_called"] is False
    assert result["checks"]["historical_dataset_readiness_model_runtime_called"] is False
    assert result["checks"]["historical_dataset_readiness_ml_training_run"] is False
    assert result["checks"]["historical_dataset_readiness_learned_model_evaluation_run"] is False
    assert result["checks"]["historical_dataset_readiness_ml_ready_tensor_export_created"] is False
    assert result["checks"]["historical_model_training_sandbox_fixture_run"] is True
    assert result["checks"]["historical_model_training_plan_check_generated"] is True
    assert result["checks"]["historical_model_training_run_report_generated"] is True
    assert result["checks"]["historical_model_evaluation_report_generated"] is True
    assert result["checks"]["historical_model_metrics_report_generated"] is True
    assert result["checks"]["historical_model_artifact_manifest_generated"] is True
    assert result["checks"]["historical_model_training_local_only"] is True
    assert result["checks"]["historical_model_training_offline_only"] is True
    assert result["checks"]["historical_model_training_chronological_split_used"] is True
    assert result["checks"]["historical_model_training_no_random_shuffle"] is True
    assert result["checks"]["historical_model_training_dummy_models_available"] is True
    assert result["checks"]["historical_model_training_optional_sklearn_fail_closed"] is True
    assert result["checks"]["historical_model_training_report_only"] is True
    assert result["checks"]["historical_model_training_non_executable"] is True
    assert result["checks"]["historical_model_training_no_runtime_signal"] is True
    assert result["checks"]["historical_model_training_no_order_candidate"] is True
    assert result["checks"]["historical_model_training_no_live_inference"] is True
    assert result["checks"]["historical_model_training_no_broker_path"] is True
    assert result["checks"]["historical_model_training_no_live_prod"] is True
    assert result["checks"]["historical_model_training_no_network"] is True
    assert result["checks"]["historical_model_training_no_cloud_llm"] is True
    assert result["checks"]["historical_model_training_no_local_llm_runtime"] is True
    assert result["checks"]["historical_model_experiment_registry_fixture_run"] is True
    assert result["checks"]["historical_model_experiment_registry_report_generated"] is True
    assert result["checks"]["historical_model_comparison_report_generated"] is True
    assert result["checks"]["historical_model_risk_review_generated"] is True
    assert result["checks"]["historical_model_promotion_block_report_generated"] is True
    assert result["checks"]["historical_model_experiment_lineage_report_generated"] is True
    assert result["checks"]["historical_model_experiment_report_only"] is True
    assert result["checks"]["historical_model_experiment_non_executable"] is True
    assert result["checks"]["historical_model_experiment_no_runtime_signal"] is True
    assert result["checks"]["historical_model_experiment_no_order_candidate"] is True
    assert result["checks"]["historical_model_experiment_no_live_inference"] is True
    assert result["checks"]["historical_model_experiment_no_deployment"] is True
    assert result["checks"]["historical_model_experiment_no_paper_trading"] is True
    assert result["checks"]["historical_model_experiment_no_broker_path"] is True
    assert result["checks"]["historical_model_experiment_no_live_prod"] is True
    assert result["checks"]["historical_model_experiment_no_network"] is True
    assert result["checks"]["historical_model_experiment_no_cloud_llm"] is True
    assert result["checks"]["historical_model_experiment_no_local_llm_runtime"] is True
    assert result["checks"]["historical_model_experiment_promotion_blocked_by_default"] is True
    assert result["checks"]["historical_signal_candidate_fixture_run"] is True
    assert result["checks"]["historical_signal_candidate_build_generated"] is True
    assert result["checks"]["historical_signal_candidate_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_safety_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_gap_report_generated"] is True
    assert result["checks"]["historical_signal_candidate_audit_record_generated"] is True
    assert result["checks"]["historical_signal_candidate_report_only"] is True
    assert result["checks"]["historical_signal_candidate_non_executable"] is True
    assert result["checks"]["historical_signal_candidate_local_only"] is True
    assert result["checks"]["historical_signal_candidate_offline_only"] is True
    assert result["checks"]["historical_signal_candidate_no_runtime_signal"] is True
    assert result["checks"]["historical_signal_candidate_no_order_candidate"] is True
    assert result["checks"]["historical_signal_candidate_no_live_inference"] is True
    assert result["checks"]["historical_signal_candidate_no_deployment"] is True
    assert result["checks"]["historical_signal_candidate_no_paper_trading"] is True
    assert result["checks"]["historical_signal_candidate_no_broker_path"] is True
    assert result["checks"]["historical_signal_candidate_no_live_prod"] is True
    assert result["checks"]["historical_signal_candidate_no_network"] is True
    assert result["checks"]["historical_signal_candidate_no_provider_api"] is True
    assert result["checks"]["historical_signal_candidate_no_cloud_llm"] is True
    assert result["checks"]["historical_signal_candidate_no_local_llm_runtime"] is True
    assert result["checks"]["historical_signal_candidate_no_buy_sell_order_execution"] is True
    assert result["checks"]["historical_signal_candidate_parquet_unsupported"] is True
    assert result["checks"]["historical_paper_trading_fixture_run"] is True
    assert result["checks"]["historical_paper_trading_run_generated"] is True
    assert result["checks"]["historical_paper_trading_decision_generated"] is True
    assert result["checks"]["historical_paper_trading_order_intent_generated"] is True
    assert result["checks"]["historical_paper_trading_fill_generated"] is True
    assert result["checks"]["historical_paper_trading_ledger_generated"] is True
    assert result["checks"]["historical_paper_trading_position_generated"] is True
    assert result["checks"]["historical_paper_trading_trade_generated"] is True
    assert result["checks"]["historical_paper_trading_performance_report_generated"] is True
    assert result["checks"]["historical_paper_trading_safety_report_generated"] is True
    assert result["checks"]["historical_paper_trading_gap_report_generated"] is True
    assert result["checks"]["historical_paper_trading_audit_record_generated"] is True
    assert result["checks"]["historical_paper_trading_paper_only"] is True
    assert result["checks"]["historical_paper_trading_simulated_only"] is True
    assert result["checks"]["historical_paper_trading_non_executable"] is True
    assert result["checks"]["historical_paper_trading_local_only"] is True
    assert result["checks"]["historical_paper_trading_offline_only"] is True
    assert result["checks"]["historical_paper_trading_read_only_input"] is True
    assert result["checks"]["historical_paper_trading_no_real_order"] is True
    assert result["checks"]["historical_paper_trading_no_real_order_intent"] is True
    assert result["checks"]["historical_paper_trading_no_broker_api"] is True
    assert result["checks"]["historical_paper_trading_no_account_api"] is True
    assert result["checks"]["historical_paper_trading_no_order_api"] is True
    assert result["checks"]["historical_paper_trading_no_kiwoom_api"] is True
    assert result["checks"]["historical_paper_trading_no_ls_api"] is True
    assert result["checks"]["historical_paper_trading_no_broker_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_kiwoom_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_ls_mock_api"] is True
    assert result["checks"]["historical_paper_trading_no_live_trading"] is True
    assert result["checks"]["historical_paper_trading_no_live_prod"] is True
    assert result["checks"]["historical_paper_trading_no_network"] is True
    assert result["checks"]["historical_paper_trading_no_provider_api"] is True
    assert result["checks"]["historical_paper_trading_no_cloud_llm"] is True
    assert result["checks"]["historical_paper_trading_no_local_llm_runtime"] is True
    assert result["checks"]["historical_paper_trading_no_external_execution"] is True
    assert result["checks"]["historical_paper_trading_parquet_unsupported"] is True
    assert result["checks"]["investing_crawler_called"] is False
    assert result["checks"]["finviz_scraper_called"] is False
    assert result["checks"]["news_ingestion_called"] is False
    assert result["checks"]["gemini_called"] is False
    assert result["checks"]["ls_api_called"] is False
    assert result["checks"]["account_api_called"] is False
    assert result["checks"]["order_api_called"] is False
    assert result["checks"]["prompt_pack_fixture_run"] is True
    assert result["checks"]["prompt_pack_validation_run"] is True
    assert result["checks"]["prompt_pack_gap_report_run"] is True
    assert result["checks"]["llm_called"] is False
    assert result["checks"]["real_model_called"] is False
    assert result["checks"]["strategy_track_required"] is True
    assert result["checks"]["market_profile_resolved"] is True
    assert result["checks"]["domestic_kr_only"] is True
    assert result["checks"]["normalized_realtime_event_consumed"] is True
    assert result["checks"]["scanner_candidate_report_generated"] is True
    assert result["checks"]["scanner_candidate_consumed"] is True
    assert result["checks"]["technical_evidence_context_checked"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["candidate_evaluation_report_generated"] is True
    assert result["checks"]["normalized_realtime_event_sequence_consumed"] is True
    assert result["checks"]["scanner_candidate_trace_generated"] is True
    assert result["checks"]["candidate_evaluation_trace_generated"] is True
    assert result["checks"]["replay_metrics_report_generated"] is True
    assert result["checks"]["promotion_readiness_report_generated"] is True
    assert result["checks"]["replay_evaluation_report_consumed"] is True
    assert result["checks"]["single_replay_comparison_generated"] is True
    assert result["checks"]["calibration_pack_aggregated"] is True
    assert result["checks"]["policy_candidate_comparison_generated"] is True
    assert result["checks"]["promotion_gate_report_generated"] is True
    assert result["checks"]["promotion_gate_pack_level_only"] is True
    assert result["checks"]["promotion_gate_report_consumed"] is True
    assert result["checks"]["candidate_evaluation_report_consumed"] is True
    assert result["checks"]["paper_shadow_explicit_opt_in_required"] is True
    assert result["checks"]["paper_shadow_journal_generated"] is True
    assert result["checks"]["paper_shadow_candidate_level_entries"] is True
    assert result["checks"]["paper_shadow_review_report_generated"] is True
    assert result["checks"]["paper_shadow_review_summary_derived_from_entries"] is True
    assert result["checks"]["paper_shadow_non_executable"] is True
    assert result["checks"]["strategy_track_required_for_trading_advisory"] is True
    assert result["checks"]["market_profile_required_for_trading_advisory"] is True
    assert result["checks"]["profitability_context_checked"] is True
    assert result["checks"]["model_runtime_called"] is False
    assert result["checks"]["cloud_llm_called"] is False
    assert result["checks"]["kiwoom_api_called"] is False
    assert result["checks"]["broker_api_called"] is False
    assert result["checks"]["credentials_accessed"] is False
    assert result["checks"]["cloud_backend_used"] is False
    assert result["checks"]["model_downloaded"] is False
    assert result["checks"]["orders_created"] is False
    assert result["checks"]["order_intent_created"] is False
    assert result["checks"]["order_drafts_created"] is False
    assert result["checks"]["execution_approval_enabled"] is False
    assert result["checks"]["live_or_prod_used"] is False
    assert result["checks"]["strategy_track_comparison_count"] == 1
